main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

#to pass the date in the URL we need to conver it as a string using a custom path converter <date:...>
from django.urls import path, register_converter
from main_app.dateconverter import DateConverter
register_converter(DateConverter, 'date')

urlpatterns = [
    path('', views.home, name="home"),
    #auth
    path('registration/signup/', views.signup, name='signup'),

    path ('about/', views.about, name="about"),
# VIEW
    path ('plants/', views.plants_index, name = "plants_index"),
    path ('plantsdb/', views.dbPlants_index, name = "plantsDB_index"),
    
    path ('socialfeed/', views.social_plants_feed, name = "social_plants_feed"),
# DETAILS
    path ('plants/<int:plant_id>', views.plant_details, name = "plant_details"),
    path ('plantsdb/<int:plant_id>', views.dbplant_info, name = "plantdb_info"),
#INTERACTIONS
#water plants
    path ('plants/<int:plant_id>/update_watering_date/<date:today>', views.update_watering_date, name = 'update_watering_date'),

#make public on the social feed
    path  ('plants/<int:plant_id>/social_status_switch', views.social_status_switch, name = 'social_status_switch'),

#make public on the social feed
    path  ('plants/<int:plant_id>/health_toggle', views.health_toggle, name = 'health_toggle'),

    #class paths are passed .as_view() to render the class defaults
#ADD PLANTS
    path ('plants/add', views.OwnedPlantAdd.as_view(), name ="plant_add"),
    path ('plants/create', views.DbPlantCreate.as_view(), name ="plant_create"),
#UPDATE PLANTS
    path ('plants/<int:pk>/update/', views.OwnedPlantUpdate.as_view(), name="plant_update"),
#REMOVE PLANTS
    path ('plants/<int:pk>/delete/', views.OwnedPlantDelete.as_view(), name='plant_delete'),
# UPLOAD PHOTO
    path('plants/<int:plant_id>/add_photo/', views.add_photo, name='add_photo'),
    path('plantsdb/<int:plant_id>/add_photo/', views.add_photo, name='add_dbphoto'),
]

plantparenthood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main_app.urls')),

    #authentication
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
#imports dates so we can calculate times between waterings
from datetime import datetime
from django.utils import timezone
# Create your models here.

class DbPlant(models.Model):
    common_name = models.CharField(max_length=50)
    botanical_name = models.CharField(max_length=50)
    description = models.TextField(max_length=150)
    time_till_dry = models.IntegerField()
    #DB INFO ONLY
    added_at = models.DateField(auto_now_add=True)
    added_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.common_name

    def get_absolute_url(self):
        return reverse('plant_details', kwargs={'plant_id': self.id})


class OwnedPlant(models.Model):
    type = models.ForeignKey(DbPlant,  related_name='plant_type', on_delete=models.CASCADE, limit_choices_to={'published': True},)
    nickname = models.CharField(max_length=50)
    public=  models.BooleanField(default = False)
    healthy=  models.BooleanField(default = True)
    watered = models.BooleanField (default = False)
    #time_till_dry = models.IntegerField()
    watering_date = models.DateField(default=timezone.now)
    adopted_since = models.DateField(default=timezone.now)
    comments = models.TextField(max_length=150, default="No comments yet")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nickname

    def get_absolute_url(self):
        return reverse('plant_details', kwargs={'plant_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    plant = models.ForeignKey(OwnedPlant, on_delete=models.CASCADE)
   

    def __str__(self):
        return f'Photo for plant_id: {self.plant_id} @{self.url}'

class DbPhoto(models.Model):
    url = models.CharField(max_length=200)
    plant = models.ForeignKey(DbPlant, on_delete=models.CASCADE)
   

    def __str__(self):
        return f'Photo for plant_id: {self.plant_id} @{self.url}'

main_app/views.py
from multiprocessing import current_process
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse

#I don;t think we need it but I leave it here as a concept. I think instead of using
#a custom form a simple button on a form on the view will work
######## from .forms import WateringForm #########

#import form for authetication signup
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
#user display and management
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required 
from django.contrib.auth.mixins import LoginRequiredMixin # research StaffuserRequiredMixin

# custom models being used
from .models import DbPlant, OwnedPlant, Photo, DbPhoto

#for the photo implementation
from plantparenthood.settings import ACCESS_KEY, ACCESS_ID

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'cat-collector-eric-photos'

#Remove this line for clean up once we implement the proper views renders
from django.http import HttpResponse




# User authentication
def signup(request):
    #Define taks for handling POST request
    form = UserCreationForm()
    error_message = ''
    if request.method == 'POST':
        #capture form inputs from user creation form
        form = UserCreationForm(request.POST)
        #validate the form inputs
        if form.is_valid():
            # save the input values as a new user to the database
            user = form.save()
            #programmatically log the user in
            login(request, user)
            #redirect user to the index page
            return redirect('plants_index')
        #if form is invalid, handle error
        else:
            error_message = 'Invalid credentials'
    #Define taks for handling GET request
    context = {'form': form, 'error_messages' : error_message}
    #render template with empty form
    return render(request, 'registration/signup.html', context)

# Define the home view
def home(request):
    return render(request, 'home.html', {'page_name': 'Home'})

def about(request):
    return render(request, 'about.html', {'page_name': "About"} )

 # User interaction with DB 
def dbPlants_index(request):
 #IN THE BASE HTML, THE USER HAS TO BE CHECKED AGAINST TO ONLY SHOW BOTH PUBLIC FEED AND THE DB
    plants = DbPlant.objects.filter(published = True)
    return render(request, 'plants/dbindex.html', { 'page_name' : 'Plant Database', 'plants':plants} )

def social_plants_feed(request):
    plants = OwnedPlant.objects.filter(public = True)
    return render(request, 'plants/social_feed.html', { 'page_name' : 'Social Feed', 'plants':plants} )



def plants_index(request):
  if request.user:
    plants = OwnedPlant.objects.filter(user = request.user)
    return render (request, 'plants/index.html', { 'page_name' : 'My Owned Plants', 'plants':plants} )

def plant_details(request, plant_id):
    plant = OwnedPlant.objects.get(id=plant_id)
    return render (request, 'plants/details.html', {'page_name':'Plant Details', 'plant': plant})

def dbplant_info(request, plant_id):
    plant = DbPlant.objects.get(id=plant_id)
    return render (request, 'plants/details.html', {'page_name':'Plant Info Sheet', 'plant': plant})

#INTERACTIONS
#I think we wrap all three interactions - watering, health and visibility under a single view called toggles or interactions.

def health_toggle(request, plant_id):
    current_plant = OwnedPlant.objects.get(id=plant_id)
    current_plant.healthy= not current_plant.healthy
    current_plant.save(update_fields=['healthy'])
    return redirect(request.META['HTTP_REFERER'])
    

def social_status_switch(request, plant_id):
    current_plant = OwnedPlant.objects.get(id=plant_id)
    current_plant.public = not current_plant.public
    current_plant.save(update_fields=['public'])
    return redirect(request.META['HTTP_REFERER'])

# def add_photo(request):
#   return HttpResponse('<h1>Add a photo</h1>')

def update_watering_date(request, plant_id, today):
  watered_plant = OwnedPlant.objects.get(id=plant_id)
  watered_plant.watering_date=today

  watered_plant.save(update_fields=['watering_date'])
  return redirect('plant_details', plant_id=plant_id)



def add_photo(request, plant_id):
    # capture the photo file from form submission
    photo_file = request.FILES.get('photo-file')
    # check if a file is present
    if photo_file:
        # initialize the boto3 s3 service
        s3 = boto3.client('s3')
        # create a unique id for each photo file
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # attempt to upload the file asset to AWS s3
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # generate a url based on the returned value of uploading to AWS
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # associate the cat to the new photo instance
            # store the url as a value in the photo url attribute
            if '/plantsdb/' in request.path:
                photo = DbPhoto(url=url, plant_id=plant_id)
            else:     
                 photo = Photo(url=url, plant_id=plant_id)
            photo.save()
            

        except Exception as error:
            print('An error has occurred')
            print(error)
    if '/plantsdb/' in request.path:
        return redirect('plantdb_info', plant_id=plant_id)
    else:
        return redirect('plant_details', plant_id=plant_id)
#CLASS BASED VIEWS
class OwnedPlantAdd(LoginRequiredMixin, CreateView):
    model = OwnedPlant
    fields= ("type", "nickname",)

    def get_success_url(self):
        return reverse('plant_details', kwargs={'plant_id':self.object.pk})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class OwnedPlantUpdate(LoginRequiredMixin, UpdateView):
#remove above and uncomment when log ins are set up and implemented for the super users    
# class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = OwnedPlant
    fields = ("type", "nickname", "watering_date", "adopted_since", "comments")

class OwnedPlantDelete(DeleteView):
#remove above and uncomment when log ins are set up and implemented for the super users
# class PlantDelete(LoginRequiredMixin, DeleteView):
    model = OwnedPlant
    success_url = '/plants/'

# Admin and staff interactions

class DbPlantCreate(LoginRequiredMixin, CreateView):
    model = DbPlant
    fields= ("common_name", "botanical_name", "description", "time_till_dry")

    def get_success_url(self):
        return reverse('plantdb_info', kwargs={'plant_id':self.object.pk})
    
    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super().form_valid(form)
    
   
# MANAGEABLE FROM THE ADMIN PANEL - COMMENTED OUT FOR NOW

# class DbPlantUpdate(LoginRequiredMixin, UpdateView):
# #remove above and uncomment when log ins are set up and implemented for the super users    
# # class PlantUpdate(LoginRequiredMixin, UpdateView):
#     pass

# class DbPlantDelete(DeleteView):
# #remove above and uncomment when log ins are set up and implemented for the super users
# # class PlantDelete(LoginRequiredMixin, DeleteView):
#     pass

main_app/templates/plants/dbindex.html
{% extends 'base.html' %}
{% load custom_time_functions %}
{% load static %}

{% block content %}
    <h1>{{page_name}}</h1>
    {% for plant in plants %}
    <div class="col s12 m7">
        <a href ="/plantsdb/{{ plant.id }}">
            <div class="card horizontal">
                <div class="card-image">
                    {% if plant.dbphoto_set.first %}
                    <img src="{{ plant.dbphoto_set.first.url }}" alt="{{ plant.name }}">
                    {% else %}
                    <img src="{% static "imgs/plants/db-use/admin.png"%}" style="width: 100%";>
                    <p>Awaiting admin photo upload</p>
                    {% endif %}
                    <span class="card-title"> {{plant.common_name}} <span/>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <div>
                            <span class="card-field">Botanical name: </span>
                            <p><i>{{plant.botanical_name}}</i></p>
                        </div>
                        <div>
                            <span class="card-field">Description:</span>
                            <p>{{plant.description}}</p>
                        </div>
                        <div>
                            <span class="card-field">Watering needs:</span> 
                            <p>Every {{plant.time_till_dry}} days or moist soil</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>  

    {% endfor %}
{% endblock %}

main_app/templates/plants/details.html
{% extends 'base.html' %}
{% load custom_time_functions %}
{% load static %}

{% block content %}
    <h1>{{page_name}}</h1>
    <div class="card gradient">
        <div class="card-content">
            <div class="row">
                <div class="col s6">
                    {%if plant.botanical_name%}
                    <div class="slideshow-container">
                        {% for photo in plant.dbphoto_set.all %}
                        <div class="mySlides fade">
                            <!-- <div class="numbertext">current image / total number of images</div> -->
                            <img class="roundCorners" src="{{ photo.url }}" alt="{{ plant.name }}" />
                            <div class="caption">Caption Text</div>
                        </div>
                        {% empty %}
                        <img src="{% static "imgs/plants/db-use/devils_ivy.png"%}" style="width: 100%";>
                    {% endfor %}
                    </div>
                    {%else%}
                    <div class="row">
                        <div class="slideshow-container">
                            <!-- Display user's photos -->
                            {% for photo in plant.photo_set.all %}
                            <div class="mySlides fade">
                                <!-- <div class="numbertext">current image / total number of images</div> -->
                                <img class="roundCorners" src="{{ photo.url }}" alt="{{ plant.name }}" style="width: 100%"/>
                                <div class="caption">Caption Text</div>
                            </div>
                            <!-- If user photo collection is empty or hasn't uploaded yet use the photos from DB -->
                            {% empty %}
                            {% for photo in plant.type.dbphoto_set.all%}
                            <div class="mySlides fade">
                                <!-- <div class="numbertext">current image / total number of images</div> -->
                                <img class="roundCorners" src="{{ photo.url }}" alt="{{ plant.name }}" />
                                <div class="caption">Caption Text</div>
                            </div>
                            <!-- If DB photo collection is empty, use a card panel  -->
                            {% empty %}
                            <div class="card-panel teal-text">No Photos Uploaded Yet</div>
                            {% endfor %}    
                            {% endfor %}
                            <!-- Next and previous buttons -->
                            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                            <a class="next" onclick="plusSlides(1)">&#10095;</a>
                            {% comment %} <img src="{% static "imgs/plants/db-use/devils_ivy.png"%}" style="width: 100%";> {% endcomment %}
                        </div>
                        <div style="text-align:center">
                            <span class="dot" onclick="currentSlide(1)"></span>
                            <span class="dot" onclick="currentSlide(2)"></span>
                            <span class="dot" onclick="currentSlide(3)"></span>
                        </div>
                    </div>
                    {% endif %}
                    {%if plant.botanical_name%}
                        {% if request.user.is_staff %}
                        <div class="row">
                            <form
                            action="{% url 'add_dbphoto' plant.id %}"
                            method="POST"
                            class="card-panel roundCorners addPhoto center"
                            enctype="multipart/form-data"
                            >
                            {% csrf_token %}
                            <input type="file" name="photo-file" />
                            <input class="btn green lighten-3" type="submit" value="Add Photo" />
                            </form>
                        </div>
                        {% endif %}
                    {% else %}
                    <div class="row">
                        <form
                        action="{% url 'add_photo' plant.id %}"
                        method="POST"
                        class="card-panel roundCorners addPhoto center"
                        enctype="multipart/form-data"
                        >
                        {% csrf_token %}
                        <input type="file" name="photo-file" />
                        <input class="btn green lighten-3" type="submit" value="Add Photo" />
                        </form>
                    </div>
                    {% endif %}
                </div>
                <div class="col s6 bottom description">
                    {%if plant.botanical_name%}                 
                    <div>
                        <span class="bold">Common name:</span> 
                        <p>{{plant.common_name}}</p>
                    </div>
                    <div>
                        <span class="bold">Botanical name:</span> 
                        <p><i>{{plant.botanical_name}}</i></p>
                    </div>
                    <div>
                        <span class="bold">Description:</span>
                        <p> {{plant.description}}</p>
                    </div>
                    <div>
                        <span class="bold">Watering needs:</span> 
                        <p>Every {{plant.time_till_dry}} days or moist soil</p>
                    </div>
                        
                    {%else%}
                    <span class="card-title bold"> {{plant.nickname}} </span>
                    <span class="bold">Type: </span>{{plant.type.common_name}}
                </div>
                <div class = "col s6">
                    <div class="row">
                        <div class="col s6">
                            <span class="bold">Comments:</span>
                            {%if plant.comments %}
                            <p class="card horizontal">{{plant.comments}}</p>
                            {% else %}
                            <p>No comments yet. Edit the card to input</p>
                            {% endif %}
                            <p class="bold">Last Watering: {{plant.watering_date}}</p>
                            {% today_date as today %}
                            {%days_until plant.watering_date plant.type.time_till_dry as days_until%}
                            {%for value in days_until|times %}
                            <div class="col S{{plant.type.time_till_dry}} blue lighten-5">
                                💧
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col s6">
                            {% if days_until >= 0 %}
                            <span class="bold">Plant Status: </span><span class="green-text">Plant is happy and still watered</span>
                            {% else %}
                            Plant Status: <span class="red-text">Plant needs watering</span>
                            {% endif %}
                            <br>
                            {% if days_until <= plant.type.time_till_dry %}
                            <span class="bold">Plant Status: </span><span class="blue-text">Watered
                            <form action="{% url 'update_watering_date' plant.id  today %}" method="post">
                                {% csrf_token %}
                                <button class="btn blue lighten-4">Water Again</button>
                            </form></span>
                            {% else %}               
                            <span><p class="red-text">Needs Water</p>
                                <form action="{% url 'update_watering_date' plant.id  today %}" method="post">
                                    {% csrf_token %}
                                    <button class="blue lighten-1">Water</button>
                                </form></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s6 center bottom">
                            <form action="{% url 'health_toggle' plant.id %}" method="post">
                                {% csrf_token %}
                                <p>
                                    <label onclick="this.form.submit()">
                                        {% if plant.healthy %}
                                        <input type="checkbox" checked="checked" />
                                        {% else %}
                                        <input type="checkbox" />
                                        {% endif %}
                                        <span>This plant is healthy</span>
                                    </label>
                                </p>
                            </form>       
                        </div>
                        <div class="col s6 center bottom">
                            <form action="{% url 'social_status_switch' plant.id %}" method="post">
                                {% csrf_token %}
                                <p>
                                    <label onclick="this.form.submit()">
                                        {% if plant.public %}
                                        <input type="checkbox" checked="checked" />
                                        {% else %}
                                        <input type="checkbox" />
                                        {% endif %}
                                        <span>Share on Public feed</span>
                                    </label>
                                </p>
                            </form>
                        </div>
                        <div class="col s12 card-action">
                            <a class="btn yellow darken-2" href="{% url 'plant_update' plant.id %}">Edit</a>
                            <a class="btn red lighten-1" href="{% url 'plant_delete' plant.id %}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
{% endif %}      
{% endblock %}

<script>
//     document.addEventListener("DOMContentLoaded", ()=> {
//         let slideIndex = 1;
// showSlides(slideIndex);

// // Next/previous controls
// function plusSlides(n) {
//     showSlides(slideIndex += n);
// }

// // Thumbnail image controls
// function currentSlide(n) {
//     showSlides(slideIndex = n);
// }

// function showSlides(n) {
//     let i;
//     let slides = document.getElementsByClassName("mySlides");
//     let dots = document.getElementsByClassName("dot");
//     console.log(slides, dots);
//     if (n > slides.length) {slideIndex = 1}
//     if (n < 1) {slideIndex = slides.length}
//     for (i = 0; i < slides.length; i++) {
//         slides[i].style.display = "none";
//     }
//     for (i = 0; i < dots.length; i++) {
//         dots[i].className = dots[i].className.replace(" active", "");
//     }
//     slides[slideIndex-1].style.display = "block";
//     dots[slideIndex-1].className += " active";
// }
//     })

</script>

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% load custom_time_functions %}
{% load static %}

{% block content %}
    <h1>{{page_name}}</h1>
    <div class="row">
        <div class="col s12">
            {% for plant in plants %}
            <div class="col s12 m6 l4">
                <a href ="/plants/{{ plant.id }}">
                    <div class="card">
                        <div class="card-image">
                            {% if plant.photo_set.first %}
                            <img src="{{ plant.photo_set.first.url }}" alt="{{ plant.name }}">
                            {% else %}
                            <img src="{{ plant.type.dbphoto_set.first.url }}" alt="{{ plant.name }}">
                            {% endif %}
                            <span class="card-title">{{plant.nickname}}<span/>
                            <!-- <p>Type: {{plant.type.common_name}}</p> -->
                        </div>
                        <div class="card-content">
                            <p>
                                Last Watered: {{plant.watering_date}}
                            </p>
                            {%days_until plant.watering_date plant.type.time_till_dry as days_until%}
                                <div class="waterdrop">
                                    {%for value in days_until|times %}
                                    <div class="{{plant.type.time_till_dry}}">
                                    💧
                                    </div>
                                {% endfor %}
                                </div>
                                {% if days_until >= 0%}
                                    {% if plant.healthy %}
                                    <span class="green-text">Plant is happy and still watered</span>
                                    {% else %}
                                    <span class="yellow-text">Plant is watered but has health issues</span>
                                    {% endif %}
                                {% else %}
                                    {% if plant.healthy %}
                                    <span class="red-text">Plant needs watering</span>
                                    {% else %}
                                    <span class="red-text-darken-4">Plant need watering and has health issues</span>
                                    {% endif %}
                                {% endif %}
                            <hr>
                            <div class="align">
                                <form action="{% url 'social_status_switch' plant.id %}" method="post">
                                    {% csrf_token %}
                                    <p>
                                        <label onclick="this.form.submit()">
                                            {% if plant.public %}
                                            <input type="checkbox" checked="checked" />
                                            {% else %}
                                            <input type="checkbox" />
                                            {% endif %}
                                            <span>Share on Public feed</span>
                                        </label>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <script>
    //checkbox fix
   // const checkEl =document.getElementById('id_healthy')
   // const checkFix = document.createElement('span')
   // checkFix.innerHTML = ""
   // checkEl.parentNode.insertBefore(checkFix,checkEl.nextSibling)
    </script>

{% endblock %}

main_app/templates/plants/social_feed.html
{% extends 'base.html' %}
{% load custom_time_functions %}
{% load static %}

{% block content %}
    <h1>{{page_name}}</h1>
    {% for plant in plants %}
    <div class=" container col s6 m7 offset-m3 offset-l4">
            <div class="card horizontal">
                <div class="card-image">
                    {% if plant.photo_set.first %}
                    <img src="{{ plant.photo_set.first.url }}" alt="{{ plant.name }}">
                    {% else %}
                    <img src="{{ plant.type.dbphoto_set.first.url }}" alt="{{ plant.common_name }} image">
                    {% endif %}
                    <span class="card-title"> {{plant.nickname}} <span class="green-text darken-2"><h6 style="display:inline !important">{{plant.user.username}}</h6></span> <span/>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <div>
                            <span class="card-field">Type: </span>
                            <p>{{plant.type.common_name}}</p>
                            <span class="card-field">Botanical name: </span>
                            <p><i>{{plant.type.botanical_name}}</i></p>
                        </div>
                        <div>
                            <span class="card-field"> <span class="green-text darken-2">{{plant.user.username}}</span> comments:</span>
                            <p class="card horizontal">{{plant.comments}}</p>
                        </div>
                    </div>
                </div>
            </div>
    </div>  

    {% endfor %}
{% endblock %}